jtype: StableDiffusionGenerator
with:
  height: 512
  max_resolution: 589824 # 768x768
  n_iter: 1
  n_samples: 4
  stable_path: ../stable-diffusion
  width: 512
metas:
  py_modules:
    - executor.py